name: Validate Translations

on:
  push:
    branches:
      - main
    paths:
      - 'locales/**.json'
  workflow_dispatch:

jobs:
  check-translations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm ci

      - name: Run Translation Validator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
        run: npx ts-node scripts/checkTranslations.ts
