name: Validate Translations

on:
  push:
    branches:
      - main
    paths:
      - 'locales/**.json'
  workflow_dispatch:

jobs:
  check-translations:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Install tsx
        run: pnpm add -D tsx

      - name: Run Translation Validator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: pnpm tsx scripts/checkTranslations.ts
